blocks/cards/cards.css, blocks/cards/cards.js
Test URLs:
- After: https://card-changes--elixirsolutions--hlxsites.hlx.live/
- After: https://card-changes--elixirsolutions--hlxsites.hlx.page/aboutus/our-services
- After: https://card-changes--elixirsolutions--hlxsites.hlx.page/plansponsors
=> fixing cards issues from import

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #17
Test URLs:
- After: https://column-followup--elixirsolutions--hlxsites.hlx.live/
=> Column followup

blocks/accordion/accordion.css, blocks/accordion/accordion.js, blocks/columns/columns.css, scripts/scripts.js, styles/styles.css
Fix #6 
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/plansponsors/pharmacy/specialty-pharmacy/elixir-specialty/elixir-specialty-prescribers
- After: https://accordion--elixirsolutions--hlxsites.hlx.live/plansponsors/pharmacy/specialty-pharmacy/elixir-specialty/elixir-specialty-prescribers
=> accordion block

blocks/header/header.css, blocks/header/header.js
Fix #2 
Test URLs:
- After: https://header-search--elixirsolutions--hlxsites.hlx.live/
=> chore: header search

404.html, blocks/error-gears/error-gears.css, blocks/error-gears/error-gears.js
Fix #14 
Test URLs:
- After: https://four-oh-four--elixirsolutions--hlxsites.hlx.live/
=> Four oh four

blocks/blog-feed/blog-feed.js, blocks/blog-topics/blog-topics.js
Fix #<gh-issue-id>
Test URLs:
- After: https://tags--elixirsolutions--hlxsites.hlx.live/blog/tag?tag=Industry%20Updates
=> Blog Tag Page

blocks/blog-feed/blog-feed.js
Fix #<gh-issue-id>
Test URLs:
- After: https://blog-feed-bug--elixirsolutions--hlxsites.hlx.live/blog
=> fix first blog post does not show icon

blocks/columns/columns.css, blocks/hero/hero.css, scripts/scripts.js, styles/lazy-styles.css, styles/styles.css
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/news/lenvima-ldd
- Before: https://main--elixirsolutions--hlxsites.hlx.live/plansponsors/rxsavingsprograms/cash-discount-program
- After: https://bug-fixes--elixirsolutions--hlxsites.hlx.live/
- After: https://bug-fixes--elixirsolutions--hlxsites.hlx.live/news/lenvima-ldd
- After: https://bug-fixes--elixirsolutions--hlxsites.hlx.live/plansponsors/rxsavingsprograms/cash-discount-program
=> minor bug fixing

blocks/video/video.css, blocks/video/video.js
Fix #45 
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/blog/cystic-fibrosis-kpi
- After: https://blog-video--elixirsolutions--hlxsites.hlx.live/blog/cystic-fibrosis-kpi
=> Blog video

scripts/scripts.js
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/members/specialty-rx
- After: https://accordion-fix--elixirsolutions--hlxsites.hlx.live/members/specialty-rx
=> fix accordions with blocks inside

blocks/table/table.css, blocks/table/table.js
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.page/blog/ned
- After: https://table--elixirsolutions--hlxsites.hlx.page/blog/ned
=> chore: table block

blocks/cards/cards.css, head.html
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/plansponsors/pharmacy-benefit-management
- After: https://cards-variant--elixirsolutions--hlxsites.hlx.live/plansponsors/pharmacy-benefit-management
=> new cards variant for teaser cards

blocks/accordion/accordion.js, blocks/blog-socials/blog-socials.js, blocks/columns/columns.js, blocks/news-feed/news-feed.js, scripts/scripts.js
Test URLs:
- After: https://createElemHelper--elixirsolutions--hlxsites.hlx.live/
=> chore: add helper for creatign elements and element trees

blocks/footer/footer.css
Fix #60
Test URLs:
- After: https://footer-fix--elixirsolutions--hlxsites.hlx.live/
=> fix footer image left margin

blocks/columns/columns.css
Fix #48 
Test URLs:
- After: https://cols-fixes--elixirsolutions--hlxsites.hlx.live/
=> Cols fixes

blocks/blog-topics/blog-topics.css, styles/styles.css
Fix #57
Test URLs:
- After: https://cls--elixirsolutions--hlxsites.hlx.live/blog/what-to-know-for-the-2022-2023-flu-season
=> CLS & blog highlight styling

blocks/blog-cta/blog-cta.css, blocks/blog-socials/blog-socials.css, blocks/blog-topics/blog-topics.css, blocks/footnote/footnote.css, blocks/table/table.css, styles/styles.css
Fix #<gh-issue-id>
Test URLs:
- After: https://table-style--elixirsolutions--hlxsites.hlx.live/blog/medicare-marketing-modifications
=> Table Style

blocks/header/header.css, blocks/header/header.js
See: #78 
Test URLs:
- After: https://a11y-78--elixirsolutions--hlxsites.hlx.page
=> fix: header a11y fixes

scripts/scripts.js
Fix #81 
Test URLs:
- After: https://a11y-81-new--elixirsolutions--hlxsites.hlx.live/
=> ally: remove redundant link titles

blocks/form/form.js
Fix #84 
Test URLs:
- After: https://issue-73--elixirsolutions--hlxsites.hlx.live/
=> fix: suppress browser from validation messages

blocks/header/header.js
Fix #83 
Test URLs:
- After: https://issue-83--elixirsolutions--hlxsites.hlx.live/
=> fix: allow closing search results with escape key

blocks/breadcrumb/breadcrumb.css, blocks/breadcrumb/breadcrumb.js
Fix #80 
Test URLs:
- After: https://a11y-80-new--elixirsolutions--hlxsites.hlx.live/
=> ally: make breadcrumb a nav

blocks/blog-feed/blog-feed.js
Fix #75 
Test URLs:
- After: https://a11y-75-new--elixirsolutions--hlxsites.hlx.live/
=> a11y: change blog cards to article elements

blocks/footer/footer.css, blocks/header/header.css
Fix #72 
Test URLs:
- After: https://svg-css--elixirsolutions--hlxsites.hlx.live/
=> svg styling for header/footer

blocks/header/header.css, blocks/header/header.js
See #78
Test URLs:
- After: https://a11y-search--elixirsolutions--hlxsites.hlx.live/
=> fix: keyboard nav on search

blocks/registration-form/registration-form.css, blocks/registration-form/registration-form.js
Fix #85 
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/register-login
- After: https://issue-85--elixirsolutions--hlxsites.hlx.live/register-login
=> Register Login-Input field should have its label

blocks/blog-feed/blog-feed.css, blocks/blog-feed/blog-feed.js
Fix #79 
Test URLs:
- After: https://blog-card-fix--elixirsolutions--hlxsites.hlx.live/
=> a11y: blog card stuff

scripts/delayed.js
Fix #99 
Test URLs:
- After: https://li-tracking--elixirsolutions--hlxsites.hlx.live/
=> chore: add li tracking

blocks/columns/columns.css, blocks/header/header.css, styles/styles.css
Fix #108 
Test URLs:
- After: https://hightlights--elixirsolutions--hlxsites.hlx.live/
=> chore: full width hightlight, column icons, header fix

blocks/accordion/accordion.css, blocks/blog-cta/blog-cta.css, blocks/blog-feed/blog-feed.css, blocks/blog-socials/blog-socials.css, blocks/blog-topics/blog-topics.css, blocks/columns/columns.css, blocks/footer/footer.css, blocks/footnote/footnote.css, blocks/form/form.css, blocks/header/header.css, blocks/hero/hero.css, blocks/registration-form/registration-form.css, blocks/table/table.css, styles/styles.css
Fix #114 
Test URLs:
- After: https://color--elixirsolutions--hlxsites.hlx.live/
=> color cleanup

blocks/blog-feed/blog-feed.css, blocks/blog-topics/blog-topics.css, blocks/breadcrumb/breadcrumb.css, blocks/cards/cards.css, blocks/columns/columns.css, blocks/header/header.css, blocks/hero/hero.css, blocks/news-feed/news-feed.css, styles/styles.css
Test URLs:
- After: https://gaps--elixirsolutions--hlxsites.hlx.live/
=> chore: refactor gap to use var

blocks/hero/hero.css
Fix #125
Test URLs:
- After: https://hero-adjustments--elixirsolutions--hlxsites.hlx.live/
=> update hero height and content width

blocks/breadcrumb/breadcrumb.css, styles/styles.css
Fix #117
Test URLs:
- After: https://breadcrumb-css--elixirsolutions--hlxsites.hlx.live/
=> Update breadcrumb alignment and size

blocks/blog-cta/blog-cta.css
Fix #128
Test URLs:
- After: https://blog-cta--elixirsolutions--hlxsites.hlx.live/
=> Update spacing before and after blog-cta

blocks/columns/columns.css
Fix #123
Test URLs:
- After: https://thirds-button--elixirsolutions--hlxsites.hlx.live/
=> Remove large button style on a.button in columns thirds

blocks/blog-feed/blog-feed.js
Test URLs:
- After: https://blog-feed-limit--elixirsolutions--hlxsites.hlx.live/
=> fix: allow blog feed mini to have author config'd limit

blocks/accordion/accordion.css, blocks/blog-cta/blog-cta.css, blocks/blog-feed/blog-feed.css, blocks/blog-highlight/blog-highlight.css, blocks/blog-topics/blog-topics.css, blocks/breadcrumb/breadcrumb.css, blocks/cards/cards.css, blocks/columns/columns.css, blocks/footer/footer.css, blocks/footnote/footnote.css, blocks/form/form.css, blocks/header/header.css, blocks/hero/hero.css, blocks/news-feed/news-feed.css, blocks/registration-form/registration-form.css, blocks/table/table.css, styles/styles.css
…th the new font scale.
Fix #132
Test URLs:
- After: https://increase-font-size--elixirsolutions--hlxsites.hlx.live/
=> Update font size scale and replace hardcoded instances

blocks/accordion/accordion.css, blocks/blog-cta/blog-cta.css, blocks/blog-email-form/blog-email-form.css, blocks/blog-socials/blog-socials.css, blocks/cards/cards.css, blocks/table/table.css, package-lock.json, styles/styles.css
Fix #161
Test URLs:
- After: https://adjusting-paragraph-margins--elixirsolutions--hlxsites.hlx.live/
=> Adjusting paragraph margins

blocks/blog-feed/blog-feed.js, blocks/cards/cards.js, blocks/news-feed/news-feed.js, scripts/scripts.js, styles/styles.css, tools/sidekick/config.json, tools/sidekick/library/library.html
Test URLs:
https://block-library--elixirsolutions--hlxsites.hlx.page/tools/sidekick/library/library.html
@sforschen @janefrommaine apologies that I forgot about this for a bit, but this is ready to go. once merged will be available to authors and if needed we can make any needed tweaks to the library content that shows up
=> Block library

blocks/blog-feed/blog-feed.js
Fix #156
Test URLs:
- After: https://blog-tag--elixirsolutions--hlxsites.hlx.live/
=> Update breadcrumb and page title to display the selected blog tag

blocks/toc/toc.css, blocks/toc/toc.js
Fix #155 
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.page/drafts/shsteimer/toc
- After: https://toc--elixirsolutions--hlxsites.hlx.page/drafts/shsteimer/toc
=> chore: TOC block

scripts/scripts.js
Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/members/about-mail
- After: https://hubfs-links--elixirsolutions--hlxsites.hlx.live/members/about-mail
=> rewrite hubfs links to page.elixirsolutions.com

blocks/hero/hero.css
Fix #160
Test URLs:
- After: https://right-padding-hero-text--elixirsolutions--hlxsites.hlx.live/
=> right padding h2 adjusted

blocks/footnote/footnote.css
Fix #170
Test URLs:
- After: https://footnote-downsize-font--elixirsolutions--hlxsites.hlx.live/
=> footnote font size down one to xs

blocks/footnote/footnote.css, blocks/toc/toc.css
Fix #169 
Test URLs:
- After: https://toc-styles--elixirsolutions--hlxsites.hlx.live/
=> Toc styles

blocks/footnote/footnote.css, blocks/header/header.css, blocks/toc/toc.css
Fix #168
Test URLs:
- After: https://remove-uppercase-top-nav--elixirsolutions--hlxsites.hlx.live/
=> Remove uppercase top nav

styles/styles.css
Fix #124
Test URLs:
- After: https://alert-highlight--elixirsolutions--hlxsites.hlx.live/
=> Add alert highlight style

blocks/cards/cards.css, blocks/columns/columns.css, blocks/footer/footer.css
Fix #167
Test URLs:
- After: https://image-style-updates--elixirsolutions--hlxsites.hlx.live/
=> Image style updates

styles/styles.css
Fix #192 
Test URLs:
- After: https://button-wrap--elixirsolutions--hlxsites.hlx.live/
=> removed no wrap from buttons

scripts/delayed.js
Fix #194
Test URLs:
- After: https://hs-tracking--elixirsolutions--hlxsites.hlx.live/
=> add hs tracking code

blocks/blog-feed/blog-feed.css
Fix #190 
Test URLs:
- After: https://blog-feed-updates--elixirsolutions--hlxsites.hlx.live/
=> card radius and feed row fix

blocks/accordion/accordion.js
Fix #183
Test URLs:
- After: https://accordion-panel--elixirsolutions--hlxsites.hlx.live/
URLs with accordions:
- Sidekick Library accordion: https://accordion-panel--elixirsolutions--hlxsites.hlx.live/tools/sidekick/library/library.html?plugin=blocks&path=/library/blocks/accordion&index=0
- Contact Us: https://accordion-panel--elixirsolutions--hlxsites.hlx.live/contactus
- Members: https://accordion-panel--elixirsolutions--hlxsites.hlx.live/members
- Members > About Mail: https://accordion-panel--elixirsolutions--hlxsites.hlx.live/members/about-mail
- Members > Specialty Rx: …
=> Collapse all accordion panels by default

styles/styles.css
Fix #203 
Test URLs:
- After: https://patch-indent-ol--elixirsolutions--hlxsites.hlx.live/
=> Update ol styles.css

blocks/form/form.js
Fix #206 
Test URLs:
- After: https://form-typo-patch--elixirsolutions--hlxsites.hlx.live/
=> Update -  fixing typo form.js

README.md, blocks/columns/columns.css
Fix #210
Test URLs:
- After: https://210-various-column-updates--elixirsolutions--hlxsites.hlx.live/
=> 210 various column updates

blocks/footer/footer.css
Fix #188 
Test URLs:
- After: https://188-footer-dropshadow--elixirsolutions--hlxsites.hlx.live/
=> Updated Footer from Blue to Gray drop shadow

scripts/scripts.js
Fix #195
Test URLs:
- After: https://blog-seo--elixirsolutions--hlxsites.hlx.live/
=> Blog byline, fix issue so byline does not appear on blog feed page

blocks/hero/hero.css
Fix #187
Test URLs:
- After: https://187-full-width--elixirsolutions--hlxsites.hlx.live/
=> Background color for Full Section on Hero's

blocks/footnote/footnote.css, package-lock.json, styles/styles.css
Fix #218 
Test URLs:
- After: https://blog-list-style--elixirsolutions--hlxsites.hlx.live/
=> updating list styles for blogs

blocks/blog-cta/blog-cta.css, blocks/blog-feed/blog-feed.css
Fix #221 
Test URLs:
- After: https://blog-cta-button--elixirsolutions--hlxsites.hlx.live/
=> blog CTA button update to standard

blocks/breadcrumb/breadcrumb.css, blocks/footer/footer.css, blocks/form/form.css, blocks/header/header.css, blocks/hero/hero.css, blocks/hero/hero.js, blocks/news-feed/news-feed.css, package-lock.json, styles/styles.css
Fix #225 
Test URLs:
- After: https://adjust-margins-and-hero--elixirsolutions--hlxsites.hlx.live/
=> margins and hero adjustments

blocks/table/table.css
Fix #228 
Test URLs:
- After: https://table-row-lines--elixirsolutions--hlxsites.hlx.live/
=> add row lines to tables

blocks/spacer/spacer.css, blocks/spacer/spacer.js, styles/styles.css
Fix #240
Test URLs:
- After: https://spacer--elixirsolutions--hlxsites.hlx.live/
=> add spacer
